src/components/Slider.js
Should resolve #47 and make FF match the webkit views. 
Doesn't remove the accessibility outline though, not sure of your approach to it across the board with Firefox so left it be 👍
=> Resolve slider UI bug in FF

src/components/Slider.js, src/index.js
The Slider component still exports the same API -- but it has been updated to be a dumb component. Internally, the demo page uses a `SliderWrapper` component which isn't exported to provide a place to hold state for the demo Slider component.
=> Make Slider dumb, provide a wrapper

package.json, src/components/Dialog.js, src/components/DialogProvider.js, src/components/DialogRoot.js, src/index.js
To control the z-index of DialogRoot in context to an App without jumping through hoops, but to also account for future requirements.
* DialogProvider is now required at the top of a React tree.
* Added an optional to render-prop to DialogRoot to override the Overlay
```js
import { DialogProvider, DialogRoot, Dialog, Overlay } from 'radix-ds'
const App () => (
<DialogProvider>
{/* Dialog can be used anywhere in this React tree, nothing new. */}
<DialogRoot>{
({ active, onClick }) =>
<Overlay active={active} onClick={onClick} style={{ zIndex: 99999 }} />
}</DialogRoot>
</DialogProvider>
)
```
=> feat(dialog): Split DialogProvider from DialogRoot

src/components/Input.js
Fixes `box-shadow` issue on iOS
=> Add `appearance: none` to Input Component

packages/radix/src/components/Badge.story.tsx, packages/radix/src/components/Badge.tsx, packages/radix/src/components/Button.story.tsx, packages/radix/src/components/Button.tsx, packages/radix/src/components/GhostButton.story.tsx, packages/radix/src/components/GhostButton.tsx, packages/radix/src/components/Input.story.tsx, packages/radix/src/components/Input.tsx, packages/radix/src/components/Textarea.story.tsx, packages/radix/src/components/Textarea.tsx, packages/website/src/docs/badge.mdx, packages/website/src/docs/button.mdx, packages/website/src/docs/ghost-button.mdx, packages/website/src/docs/input.mdx, packages/website/src/docs/textarea.mdx
Instead of using `normal` and `large`, I've changed them to be `0` and `1`.
I think this is more consistent throughout the codebase now and also it's a bit more abstract.
Still don't think it's the perfect solution, but a small improvement.
Keen to hear thoughts.
=> refactor(radix): update size variants

packages/radix/src/components/Card.tsx
Prevents text 'jumping' because there is no compositing change on hover anymore.
=> fix: add will-change:transform to shadow and ghost cardlinks

packages/website/_redirects
Right now you can access the Radix docs from https://modulz-radix.netlify.com and https://radix.modulz.app, is the same website served from two different URLs.
By adding the Netlify `_redirects` file with these two rules any url accessed from the Netlify domain will be redirected to the Modulz domain.
For example:
https://modulz-radix.netlify.com/docs/playground/ will be redirected to https://radix.modulz.app/docs/playground/
=> chore(website): redirect from Netlify to Modulz domain

packages/radix/src/theme.ts
Ahoy!
I added theme typing for a better developer experience with Radix.
PS: I had to go out of my way a bit to type breakpoints as an array with property aliases, so it doesn't work as perfectly as with other properties. For example, you won't get an error for this `theme.breakpoints[10]`, although there's just 4 breakpoints. You still get typeahead support with the aliases though.
The question being are we using breakpoints as an array at all? If there're no hard reasons to keep it this way, I'd vouch for a simple object with `small, medium, large, xlarge` keys.
=> Theme typing

packages/radix/src/components/Popover.story.tsx, packages/radix/src/components/Popover.tsx, packages/website/src/docs/popover.mdx
Change `Popover` to not render the arrow by default and introduce a `showArrow` prop
=> Add a `showArrow` pop to Popover

packages/radix/src/components/Select.tsx
- Fixed a rare bug when Select text may get misaligned vertically due to how line height and borders work together
- Added a subtle hover effect
=> Select text alignment and hover styles

packages/radix/src/components/Input.tsx, packages/radix/src/components/Select.tsx, packages/radix/src/components/Textarea.tsx
- Updated Input and Textarea to use `box-shadow` for borders
- Added light grey background for disabled Input and Textarea
- Updated Textarea layout. Compare [before](https://upload.vladmoroz.com/Screenshot%202019-12-17%20at%2013.34.11.png) and [after](https://upload.vladmoroz.com/Screenshot%202019-12-17%20at%2013.36.46.png).
=> Input, Textarea and Select with box shadow border

packages/radix/src/components/Dialog.tsx, packages/radix/src/components/Input.tsx, packages/radix/src/components/Tooltip.tsx
This quick ⚡️ PR fixes a minor problem with input padding and sneaks in a couple of visual tweaks
***
- Removed the right padding so that small inputs don't cut off longer text
- Dialled a nicer text selection height in Safari
Before
After
***
Padding update.
Before
After
***
Dark overlay instead of white overlay
Before
After
=> Design updates to Input, Dialog, and Tooltip

packages/radix/src/components/Input.story.tsx, packages/radix/src/components/Input.tsx, packages/radix/src/components/Textarea.tsx, packages/website/src/docs/input.mdx, packages/website/src/docs/textarea.mdx
Closes #188
Given time and effort, I find this to be the most appropriate solution to #188 
- By default, `Input` and `Textarea` will use `cursor: text`
- If the variant `cursor="default"` is provided, it will use `cursor: default`
This will give us enough control and flexibility in Modulz to decide which type of Cursor we want to use without having to wrap it in another SC.
=> Add Cursor variant to Input and Textarea

packages/radix/src/components/Input.tsx
**Edit**: reverted to simpler symmetrical paddings.
Previous comment for history:
***
Heads up, this might be a _biiiit_ controversial, although solves a real problem. Up for discussion.
We previously ditched the right padding on inputs so that longer text isn't cut off at the side, which was apparent in the editor. However, this messes with inputs that have text aligned to center and right.
***
**Before**
***
**After**
***
Technically, this is the same as what we have for the [conditional letter spacing that depends on weight](https://github.com/modulz/radix/blob/bedb32ac7731afb5f61912d9fe2763b832707f28/packages/radix/src/components/Text.tsx#L36). Like conditional letter spacing, we won't be able to reproduce this in Modulz app when Radix is generated by Modulz; unless we factor it in. …
=> Input padding and text alignment

packages/radix/src/components/Button.tsx, packages/radix/src/components/CardLink.tsx, packages/radix/src/components/Checkbox.tsx, packages/radix/src/components/GhostButton.tsx, packages/radix/src/components/Link.tsx, packages/radix/src/components/List.tsx, packages/radix/src/components/Radio.tsx, packages/radix/src/components/Select.tsx, packages/radix/src/components/ToggleButton.tsx, packages/website/src/now.json
This PR is a pragmatic design workaround to _not_ do https://github.com/modulz/modulz/issues/657
***
Changed from blue focus ring to gray focus ring:
- Button, gray variant
- Select
- Ghost Button, inactive variant
- Toggle Button, inactive variant
- List Item, inactive variant
Added focus styles that were missing:
- Link
Changed from a thin blue focus ring to a thick one:
- Card Link
- Checkbox
- Radio
Demos:
https://radix-cpdhtbbs9.now.sh/docs/popover/
https://radix-cpdhtbbs9.now.sh/docs/ghost-button/
***
Thought process:
- I figured that doing `focus-visible` is going to open a can of worms that we don't want to deal with, no matter whether we are looking at this feature conservatively or not. So I decided to see if this issue may simply be mitigated by adjusting focus styles slightly. …
=> Revise focus styles

packages/website/src/docs/grid.mdx
The `width` and `height` props doesn't affect the grid items and are ending up as attributes in the DOM. The live example works the same without them.
=> Remove unnecessary docs props

README.md, package.json
fix the issue after cloning the repo and run command `yarn start` cause error when starting docs site. because of radix still not build.
=> fix yarn start

packages/radix/src/components/Container.tsx, packages/radix/src/theme.ts
- Set breakpoints to `px` as well since `em` breakpoints are broken in Safari. [Adam Wathan](https://adamwathan.me/dont-use-em-for-media-queries/) wrote an extensive article about it.
- Set Container units to px for consistent scaling behaviour with other components
- Slightly changed Container width to harmonise derived grid layouts to the space scale better
- Getting this in while it has almost no effects on current Container usage, so there's foundation for easier design work down the road.
***
The slightly updated container widths are based on a traditional 12-column grid:
- `25rem` computed at `375px` stays
- Only units changed
- `45rem` computed at `675px` → `685px`
- This is 12 columns at `30px` with gutters at `25px`
- `65rem` computed at `975px` → `985px`
- This is 12 columns at …
=> Fix breakpoint scaling in Safari and set container width

packages/radix-system/package.json, packages/radix-system/src/index.ts, packages/radix-system/src/system/space/index.ts, packages/radix-system/src/system/space/margin.test.tsx, packages/radix-system/src/system/space/margin.ts, packages/radix-system/src/system/space/padding.test.tsx, packages/radix-system/src/system/space/padding.ts, packages/radix-system/src/types/index.d.ts, packages/radix-system/src/utils/sx.test.tsx, packages/radix-system/src/utils/sx.ts, packages/radix-system/src/utils/variant.ts, yarn.lock
This PR Adds SX Prop to Radix System so we can implement it in Primitives.
The usage would be something like this:
```tsx
import styled from 'styled-components';
import {
sx,
SxProp,
spaceSet,
SpaceSetProps,
} from '@modulz/radix-system';
type BoxDOMProps = React.ComponentPropsWithRef<'div'>;
type BoxSystemProps = SxProp & SpaceSetProps & TextColorProps;
type BoxProps = BoxDOMProps & BoxSystemProps;
const Box = styled('div')<BoxProps>(
spaceSet,
sx
);
```
It also introduced a new `SpaceSet` which groups `padding` and `margin` system props
=> Add SX Prop in Radix System

packages/radix/.storybook/preview-head.html, packages/radix/src/components/ChromelessButton.story.tsx, packages/radix/src/components/ChromelessButton.tsx, packages/radix/src/components/Image.story.tsx, packages/radix/src/components/Image.tsx, packages/radix/src/components/Link.story.tsx, packages/radix/src/components/Link.tsx, packages/radix/src/index.ts, packages/website/src/App.js, packages/website/src/components/APISection.js, packages/website/src/components/Layout.js, packages/website/src/components/PropsTable.js, packages/website/src/components/ThemeSection.js, packages/website/src/docs/Table.mdx, packages/website/src/docs/api.mdx, packages/website/src/docs/checkbox.mdx, packages/website/src/docs/chromeless-button.mdx, packages/website/src/docs/getting-started.mdx, packages/website/src/docs/image.mdx, packages/website/src/docs/input-with-icon.mdx, packages/website/src/docs/link.mdx, packages/website/src/docs/radio.mdx, packages/website/src/docs/slider.mdx, packages/website/src/docs/switch.mdx, packages/website/src/docs/theme.mdx, packages/website/src/templates/doc-page.js
- new variants for `Link`
- exporting `Image` 
- new `ChromelessButton`
- updated Docs
Closes #229
=> Link update and export Image

packages/radix/src/components/Table.tsx, packages/website/src/docs/Table.mdx
Currently, `th` and `td` are offset in Table due to padding on the right. It's not a big deal but stood out to me since it can cause unnecessary wrapping of text.
=> fix(Table): padding right offset

packages/radix/package.json, packages/website/package.json, packages/website/src/docs/menu.mdx, packages/website/src/templates/doc-page.js, yarn.lock
This PR handles disabling the lock in a different way now that we have the DebugContextProvider.
I'm currently using the frontmatter for this, which is suitable, and it's all completely different in the real styleguide anyway.
=> Handle disable lock in Menu story

packages/radix/src/components/Select.tsx
Adding a hover style to the ghost Select variant that matches the Ghost Button hover style
=> Add hover style to the ghost Select variant

packages/radix/src/components/Textarea.story.tsx
Was playing around with the radix storybook and found this small typo.
=> Fix typo in the Textarea story name

packages/radix/src/components/Subheading.story.tsx, packages/radix/src/components/Subheading.tsx, packages/radix/src/index.ts, packages/website/src/docs/chromeless-button.mdx, packages/website/src/docs/menu.mdx, packages/website/src/docs/subheading.mdx
Adding a Subheading component to use for section headings in the Editor and in the marketing blog.
***
=> Add Subheading component

packages/radix/package.json, packages/radix/src/components/Avatar.tsx, packages/radix/src/components/Subheading.tsx, packages/website/package.json, packages/website/src/App.js, packages/website/src/components/NavItem.js, yarn.lock
- Updated Avatar design. Using lighter weight, larger font size, lighter background. Closes #244. 
- Changed Subheading letter spacing `0.035em` → `0.05em`
- Changed docs navigation to use the Subheading
- Changed docs links with External Link Icon to open in new tab
- Updated Radix Icons version to latest. Still need to bump up Radix Icons in Primitives.
=> Avatar design update and more

packages/radix/src/components/Avatar.story.tsx, packages/radix/src/components/Avatar.tsx, packages/website/src/docs/avatar.mdx
Yet another Avatar design update and a black (dark?) variant to use in Modulz for the default design system logos.
The variants are named `variant="gray"` and `variant="black"`
=> Avatar design update and a black variant

packages/radix/src/components/Dialog.tsx
Adding a slight optical compensation to the dialog margin so it _feels_ centered vertically, since perfect vertical centering makes the dialog look lower than it really is.
Optical centering:
Perfect centering:
=> Optically-centered dialog

packages/radix/src/components/Input.tsx
Adding a workaround for a tiny visual bug in Chrome.
Before:
After:
When input is positioned ambiguously — imagine it's vertically centered on the screen so its position seems to be calculated with subpixel-level precision — there is a schism between how the actual input “box” is placed and how its text baseline is placed. In this case resizing the viewport height may introduce slight baseline misalignments and make text look not centered vertically within the input.
This happens because actual input text is rendered by a shadow DOM element, which doesn't use the line height of the input. Instead, it uses the default `line-height: normal`, which means `1.2`.
So:
* The input height is 35, the font size is 13
* The shadow DOM element height is Math.ceil(13 * 1.2) = 16
* 35 - 16 = 19 pixels …
=> Fix the input baseline position

packages/website/src/components/PropsTable.js
I may be in the wrong here, but I think this does not look ideal 🙈
I think it should be fine to wrap here in all cases, but if not, feel free to close this 🙃
=> fix(PropsTable): cell white space wrapping

components/TextField.tsx
- Chrome: fixes baseline position when emoji are used in the TextField
- Chrome: fixes baseline position when TextField is positioned with % or vh margin
- Safari: fixes 0.5px baseline misalignment, fixes clipped characters
***
Tests for posterity:
https://ys2te.csb.app/
https://codesandbox.io/s/horrible-misalignment-wfhw9?file=/src/App.js
=> Update TextField line height
