src/components/Flexbox.js, src/components/Grid.js, src/components/Section.js, src/components/Text.js, src/utilities/BackgroundColor.js, src/utilities/Color.js, src/utilities/FlexItem.js, src/utilities/Height.js, src/utilities/Leading.js, src/utilities/Margin.js, src/utilities/NegativeMargin.js, src/utilities/Offset.js, src/utilities/Overflow.js, src/utilities/Padding.js, src/utilities/PointerEvents.js, src/utilities/Position.js, src/utilities/TextAlign.js, src/utilities/Width.js
**Radix optimizations.**
There is still more that can be done, but this should be good for us until someone is tasked with maintaining radix.
Tested it on the marketing website and scripting now takes about 2.5 sec instead of the old ~40 sec that I used to have on my same PC before
closes #104
=> Life is an array of props

packages/radix/src/components/Input.story.tsx, packages/radix/src/components/Input.tsx, packages/radix/src/components/Select.story.tsx, packages/radix/src/components/Select.tsx, packages/radix/src/components/Slider.story.tsx, packages/radix/src/components/Slider.tsx, packages/radix/src/components/ToggleButton.story.tsx, packages/radix/src/components/ToggleButton.tsx, packages/radix/src/components/playground.story.tsx, packages/website/src/docs/input.mdx, packages/website/src/docs/select.mdx, packages/website/src/docs/slider.mdx, packages/website/src/docs/toggle-button.mdx
This PR implements a `highlight` variant to:
- `ToggleButton`
- `Slider`
- `Select`
- `Input`
This PR also resolves #125
=> add `highlight` variant to some components

packages/radix/src/components/Table.tsx, packages/website/src/components/DocLayout.js
=> style(website): design tweaks

packages/radix/src/components/Menu.tsx, packages/website/src/components/DocLayout.js, packages/website/src/components/NavItem.js, packages/website/src/docs/menu.mdx
=> feat(radix): expose minHeight and padding to `MenuItem` Component

packages/radix/src/components/Card.story.tsx, packages/radix/src/components/Heading.story.tsx, packages/radix/src/components/Heading.tsx, packages/radix/src/components/Menu.story.tsx, packages/radix/src/components/Pipe.story.tsx, packages/radix/src/components/Text.story.tsx, packages/radix/src/components/Text.tsx, packages/radix/src/fonts/index.ts, packages/website/src/App.js, packages/website/src/docs/card-link.mdx, packages/website/src/docs/flex.mdx, packages/website/src/docs/heading.mdx, packages/website/src/docs/text.mdx, packages/website/src/templates/doc-page.js
=> fix(radix): `fontWeight` prop in `Heading` and `Text`

packages/radix/src/components/Switch.tsx, packages/radix/src/components/ToggleButton.story.tsx, packages/radix/src/components/ToggleButton.tsx, packages/website/src/docs/toggle-button.mdx
- Added a smaller Toggle Button size
- Removed an orphaned Toggle Button variant `"normal"`
- Normalised focused Toggle Button outline alignment between active and not active states
- Slightly adjusted the color of Switch handle when it's pressed
=> Smaller Toggle Button

packages/radix/src/components/ToggleButton.story.tsx, packages/radix/src/components/ToggleButton.tsx, packages/website/src/docs/toggle-button.mdx
Added `variant="fade"` to the `ToggleButton`
=> Toggle Button — Fade variant

packages/radix/src/components/ToggleButton.tsx
- Addresses https://github.com/modulz/modulz/issues/313
- Fixes #190 
***
=> Update Toggle Button smallest size design

packages/radix/package.json, packages/radix/src/components/Dialog.story.tsx, packages/radix/src/components/Popover.story.tsx, packages/website/src/docs/dialog.mdx, packages/website/src/docs/menu.mdx, packages/website/src/docs/popover.mdx, yarn.lock
=> Upgrade Primitives

packages/radix/package.json, packages/radix/src/components/Table.tsx, packages/radix/src/index.ts, packages/website/src/components/PropsTable.js, packages/website/src/components/SystemPropsTable.js, packages/website/src/docs/Table.mdx, yarn.lock
=> Implement Table Primitive

packages/radix/src/components/Dialog.story.tsx, packages/radix/src/components/Popover.story.tsx, packages/website/src/docs/dialog.mdx, packages/website/src/docs/menu.mdx, packages/website/src/docs/popover.mdx
=> Rename `onIsOpenChange` to `isClose`

packages/radix/src/components/Avatar.story.tsx, packages/radix/src/components/Avatar.tsx, packages/radix/src/index.ts, packages/website/src/docs/avatar.mdx
Added a simple Avatar component — we already need to use one in the app.
=> Added Avatar component

packages/radix/src/components/GhostButton.story.tsx, packages/radix/src/components/GhostButton.tsx
=> Changed Ghost Button to work on blue and gray backgrounds

packages/radix/package.json, packages/radix/src/components/Switch.tsx, packages/radix/src/components/ToggleButton.tsx, packages/website/package.json, yarn.lock
=> Radix Switch using new Switch primitive

packages/radix/src/components/Avatar.story.tsx, packages/radix/src/components/Avatar.tsx, packages/website/src/docs/avatar.mdx
Adding another Avatar size since we have been consistently using two in Modulz
=> Add a larger Avatar size

packages/radix/src/components/Code.story.tsx, packages/radix/src/components/Code.tsx, packages/website/src/components/PropsTable.js, packages/website/src/docs/code.mdx, packages/website/src/templates/doc-page.js
Styling update to `Code` Component
- Removed `fade` variant (breaking change)
- Update default style
=> Update Code component Style

packages/website/src/docs/dialog.mdx
I think this makes more sense 🙂
=> fix(Dialog): refToFocusOnOpen description

packages/radix/src/GlobalStyles.tsx
Closes https://github.com/modulz/modulz/issues/1220
=> Clean up the global styles

packages/radix/src/components/Code.tsx
Closes https://github.com/modulz/radix/issues/261
=> Update Code component

packages/radix/src/components/Code.tsx
Changed Code to limit the smallest font size to `12px`
=> Smallest Code font size

packages/radix/src/components/List.tsx
=> fix(ListItem): explicitly set font family

packages/radix/src/theme.ts
We'll need to merge and release this together with https://github.com/modulz/modulz/pull/1375
=> New monospace font

index.ts
Re-export missing Stitches functions to be able to do SSR, keyframes, etc.
=> Re-export missing Stitches functions

components/Select.tsx
=> Add select caret icon

components/Flex.tsx
This is just a fix to the types in the flex polyfill that prevented the DS from bundling
=> Fix TS bundling error

package.json, stitches.config.ts, yarn.lock
- Upgrade Stitches for the grid column unit bug fix
- Remove previous auto-prefixing that caused an import issue and add manual auto-prefixing for now
=> Upgrade Stitches, fix auto-prefixing import

package.json, yarn.lock
Update to [Stitches 0.1.0](https://stitches.dev)
=> Update to Stitches Beta 0.1.0

components/Section.tsx
`ButtonCSSProp` should be `SectionCSSProp`
=> fix typo in type name

components/Avatar.tsx
Add missing avatar colors for more multiplayer options
=> Add avatar colors

pages/index.tsx
This pr removes the Banner component button from the sidebar as it is not being called somewhere.
#382
=> Removing navbar banner button
